image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose
  - docker-compose up -d --build
  # here we can install our dependencies (composer, yarn…)

tests:
  script:
    - docker-compose exec users flask cov
    - docker-compose exec users flake8 project
  after_script:
    - docker-compose down
